server:
  port: ${app_port:8761}
spring:
  application:
    name: discovery-service
eureka:
  instance:
    hostname: ${ app_hostname:localhost }
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: "https://${eureka.instance.hostname}:${server.port}/eureka"