spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: sapassword
    url: jdbc:mysql://localhost:3306/oauthdb?createDatabaseIfNotExist=true
    username: root
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        show-sql: true
    open-in-view: false